[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[phases.setup]
aptPkgs = ["ffmpeg", "python3", "python3-pip", "opus-tools", "libopus0"] 