[build]
builder = "nixpacks"
buildCommand = """
apt-get update
apt-get install -y ffmpeg
pip install -r requirements.txt
ffmpeg -version
which ffmpeg
"""

[deploy]
startCommand = "python main.py"
restartPolicyType = "on_failure"

[phases.setup]
aptPkgs = ["python3", "python3-pip", "opus-tools", "libopus0"]

[phases.build]
cmds = [
    "which ffmpeg",
    "ffmpeg -version"
] 