[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"
restartPolicyType = "on_failure"

[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y ffmpeg python3 python3-pip opus-tools libopus0",
    "pip install -r requirements.txt",
    "ffmpeg -version"
] 